const SIZE = 25;
const GRAVITY = 1;
const FPS = 60;
const WIDTH = 1600;
const HEIGHT = 900;
const WORLD_WIDTH = WIDTH * 7;
const WORLD_HEIGHT = HEIGHT * 3.5;

export { SIZE, GRAVITY, FPS, WIDTH, HEIGHT, WORLD_WIDTH, WORLD_HEIGHT };
